
<h1>JQuery Widgets Magento 2</h1>
<p>Bienvenido a la página de demostración de JQuery Widgets en Magento 2.</p>



<h1>Notacion Declarativa - Es recomendada - con separacion de responsabilidad</h1>
<div id="accordion-custom" class="accordion">
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Widget Alert | Magento 2</h4>
        </div>
    </div>
    <div data-role="content">
        <button id="show-alert-button">Mostrar Alerta</button>
    
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 2</h4>
        </div>
    </div>
    <div data-role="content"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 3</h4>
        </div>
    </div>
    <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div>

<script type="text/x-magento-init">
{
    "#accordion-custom": {
        "Kinuz_JQWidgets/js/accordion": {}
    }
}
</script>

<script type="text/x-magento-init">
{
    "#show-alert-button": {
        "Kinuz_JQWidgets/js/alert": {
            "title": "Alerta Personalizada",
            "content": "Este es un mensaje de alerta desde el JSON."
        }
    }
}
</script>

