
<h1>JQuery Widgets Magento 2</h1>
<p>Bienvenido a la página de demostración de JQuery Widgets en Magento 2.</p>



<h1>Notacion Declarativa - Es recomendada - con separacion de responsabilidad</h1>
<div id="accordion-custom" class="accordion">
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Widget Alert | Magento 2</h4>
        </div>
    </div>
    <div data-role="content">
        <button id="show-alert-button">Mostrar Alerta</button>
    
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Widget Tabs | Magento 2</h4>
        </div>
    </div>
    <div data-role="content"> 
        <div class="product data items"
            data-mage-init='{"Kinuz_JQWidgets/js/tabs": {}}'>
            <div class="item title" data-role="collapsible">
                <a class="switch" data-toggle="trigger" href="#tab-cars">Cars</a>
            </div>
            <div id="tab-cars" class="item content" data-role="content">Cars content</div>

            <div class="item title" data-role="collapsible">
                <a class="switch" data-toggle="trigger" href="#tab-movies">Movies</a>
            </div>
            <div id="tab-movies" class="item content" data-role="content">Movies content</div>

            <div class="item title" data-role="collapsible">
                <a class="switch" data-toggle="trigger" href="#tab-music">Music</a>
            </div>
            <div id="tab-music" class="item content" data-role="content">Music Content</div>
        </div>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 3</h4>
        </div>
    </div>
    <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div>

<script type="text/x-magento-init">
{
    "#accordion-custom": {
        "Kinuz_JQWidgets/js/accordion": {}
    }
}
</script>

<script type="text/x-magento-init">
{
    "#show-alert-button": {
        "Kinuz_JQWidgets/js/alert": {
            "title": "Alerta Personalizada",
            "content": "Este es un mensaje de alerta desde el JSON."
        }
    }
}
</script>

